version: "3"
services:
  frontend:
    image: frontend
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI='mongodb://mongo:27017/shopping-cart'

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
