version: "3"
services:
  frontend:
    image: asia.gcr.io/mern-shopping-cart/frontend
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - shopping-cart

  backend:
    image: asia.gcr.io/mern-shopping-cart/backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - shopping-cart
    environment:
      - MONGO_URI='mongodb://mongo:27017/shopping-cart'

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - shopping-cart
    volumes:
      - mongo-data:/data/db

networks:
  shopping-cart:
    driver: bridge

volumes:
  mongo-data:
    driver: local
